# Generated by Django 4.1.5 on 2023-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
            },
        ),
        migrations.AlterModelOptions(
            name='analytics',
            options={'verbose_name': 'Специалист по информационной безопасности', 'verbose_name_plural': 'Специалист по информационной безопасности'},
        ),
    ]
